= 카부 커뮤니티 채팅 API
:doctype: book
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:seclinks:

== 채팅 API (ChatController)
=== 채팅방 생성 성공 API
==== 요청
operation::chat-controller-test/create-room-test[snippets="http-request,request-fields"]
==== 응답
operation::chat-controller-test/create-room-test[snippets="http-response,response-fields"]
=== 채팅방 생성 실패 API
==== 요청
operation::chat-controller-test/create-room-fail-test[snippets="http-request,request-fields"]
==== 응답
operation::chat-controller-test/create-room-fail-test[snippets="http-response,response-fields"]
=== 채팅방 리스트 조회 API
==== 요청
operation::chat-controller-test/find-by-username-test[snippets="http-request,query-parameters"]
==== 응답
operation::chat-controller-test/find-by-username-test[snippets="http-response,response-fields"]
=== 채팅방 채팅내역 조회 API
==== 요청
operation::chat-controller-test/find-chat-message-test[snippets="http-request,query-parameters"]
==== 응답
operation::chat-controller-test/find-chat-message-test[snippets="http-response,response-fields"]
